### ISSUE TITLE
`The define key "process.env.ProgramFiles(x86)" contains invalid identifier "ProgramFiles(x86)"`

### ISSUE THREAD

**Issue by asherstoppard** [rw3iss/esbuild-envfile-plugin#7]
We're currently seeing the following issue when building on windows based systems. It looks like the non-alphanumeric characters (brackets) in `CommonProgramFiles(x86)` is causing an error.

Is there anyway of filtering these key/value pairs?

```
Error: Build failed with 2 errors:
error: The define key "process.env.CommonProgramFiles(x86)" contains invalid identifier "CommonProgramFiles(x86)"
error: The define key "process.env.ProgramFiles(x86)" contains invalid identifier "ProgramFiles(x86)"
    at failureErrorWithLog (C:\project\git\project-repo\node_modules\esbuild\lib\main.js:1603:15)
    at C:\project\git\project-repo\node_modules\esbuild\lib\main.js:1249:28 {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The define key "process.env.CommonProgramFiles(x86)" contains invalid identifier "CommonProgramFiles(x86)"'
    },
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The define key "process.env.ProgramFiles(x86)" contains invalid identifier "ProgramFiles(x86)"'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@luco/infra'
```

**Comment by rw3iss** [comment]
Yeah, this is why I use this script, for example:

```
module.exports = {
    getNormalizedEnvVars: () => {
        const define = {};
        const defineNoQuotes = {};

        for (const k in process.env) {
            // Bypass windows errors
            if (k === 'CommonProgramFiles(x86)' || k === 'ProgramFiles(x86)') {
                continue;
            }

            define[`process.env.${k}`] = JSON.stringify(process.env[k]);
            defineNoQuotes[`process.env.${k}`] = process.env[k];
        }

        return { define, defineNoQuotes };
    }
}
```

Then you can just use the returned 'define' (or only return define if you don't need the 'No quotes' version for some reason.

Use:

```
const { define, defineNoQuotes } = getNormalizedEnvVars();
esbuild.build({
    entryPoints: [entryFile],
    outfile: outFile,
    bundle: true,
    target: TARGET,
    logLevel: 'info',
    loader: { // built-in loaders: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary
        '.ttf': 'file',
        '.otf': 'file',
        '.png': 'file',
        '.svg': 'file'
    },
    assetNames: 'static/[name].[hash]',
    plugins: [scssPlugin, copyPlugin, postCssPlugin({ plugins: [autoprefixer] })],
    sourcemap: IS_DEV ? true : false,
    define
})
    .then(r => { console.log(`Build ${entryFile} to ${outFile} succeeded.`) })
    .catch((e) => {
        console.log("Error building:", e.message);
        process.exit(1)
    })
```
